## Conditions of Theorem 4.1 for stochastic reaction networks with monotone kinetics,
## evaluated in exact arithmetic.
##
## The conservation laws are an exact integer basis of the orthogonal complement
## of the stoichiometric subspace, obtained by the Gauss-Jordan method of
## Sauro and Ingalls, Biophys. Chem. 109 (2004) 1-15, Section 4.2; the feasibility
## questions are decided by cddlib in rational arithmetic.  No tolerance enters at
## any point, so the entries of A and B are exact.

## libraries #######################################################################################

library(rcdd)     # exact rational arithmetic (needs the GNU MP system library)
library(gmp)      # exact integer arithmetic, for conservation laws and M xi_r



## auxiliary functions #############################################################################

populateAB <- function (conservation.laws, preorder.matrix, rows = NULL) {
  checkIntegerInput(conservation.laws, "conservation.laws", allow.boundary = TRUE)
  checkIntegerInput(preorder.matrix, "preorder.matrix")
  m <- nrow(preorder.matrix)  # number of inequalities
  d <- ncol(preorder.matrix)  # number of species
  if (ncol(conservation.laws) != d) {
    stop('number of columns of matrices "conservation.laws" and "preorder.matrix" does not match')
  }
  A <- matrix(rep(0, (m+1)*d), nrow = m+1, ncol = d)
  B <- matrix(rep(0, (m+1)*d), nrow = m+1, ncol = d)
  N <- rbind(preorder.matrix, rep(0, d))  # preorder.matrix with extra 0 row
  # rows that checkConditions() can consult; the caller knows them from the
  # reaction vectors, and every other row of A and B is never read
  if (is.null(rows)) rows <- 1:(m+1)
  rows <- sort(union(rows, m+1), decreasing = TRUE)   # row m+1 first
  for (i in rows) {
    # the whole i-th row of A and of B comes from ONE description of the cone
    # generated by the columns of D: see coneRow() below
    D <- cbind(t(conservation.laws), -t(conservation.laws), t(preorder.matrix), -N[i, ])
    r <- coneRow(D, d)
    A[i, ] <- r$a
    B[i, ] <- r$b
  }
  return(list(A = A, B = B))
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

checkConditions <- function(source.complexes, reaction.vectors, conservation.laws, 
                            preorder.matrix) {
  checkIntegerInput(source.complexes, "source.complexes", nonnegative = TRUE)
  checkIntegerInput(reaction.vectors, "reaction.vectors")
  n <- nrow(source.complexes)  # number of reactions
  d <- ncol(source.complexes)  # number of species
  m <- nrow(preorder.matrix)  # number of inequalities
  if (nrow(reaction.vectors) != n) {
    stop('number of rows of matrices "source.complexes" and "reaction.vectors" does not match')
  }
  if ((ncol(reaction.vectors) != d) || (ncol(conservation.laws) != d) || 
      (ncol(preorder.matrix) != d)) {
    stop('number of columns of matrices "source.complexes", "reaction.vectors", "conservation.laws" 
          and "preorder.matrix" does not match')
  }
  # M xi_r for every reaction at once, exactly: column r of V is M xi_r
  V <- exactProduct(preorder.matrix, reaction.vectors)
  # compute matrices A and B, only the rows that can be consulted below
  AandB <- populateAB(conservation.laws, preorder.matrix, rows = neededRows(V))
  A <- AandB$A
  B <- AandB$B
  # create the output variables
  result <- 1
  ratesIneq <- matrix(rep(0, 2*n), nrow = 2)
  speciesIneq <- rbind(A[m+1, ], -B[m+1, ])
  firstFail <- ''
  # check conditions for each reaction
  for (r in 1:n) {
    vec <- V[, r]
    pos <- vec*(vec>0)
    neg <- -vec*(vec<0)
    check <- 0
    # conditions (a)
    if (all(pos == 0)) {
      check <- 1
    } else if (all(A[m+1, ]*source.complexes[r, ] == source.complexes[r, ])) {
      check <- 1
      ratesIneq[1, r] <- 1
    } else {
      for (i in 1:m) {
        e <- rep(0, m)
        e[i] <- 1
        if (all(pos == e) && all(A[i, ]*source.complexes[r, ] == source.complexes[r, ])) {
          check <- 1
          ratesIneq[1, r] <- 1
        }
      }
    }
    if (check != 1) {
      result <- 0
      firstFail <- paste('reaction', r, '/ conditions (a)')
      break
    }
    # conditions (b)
    if (all(neg == 0)) {
      check <- 2
    } else if (all(B[m+1, ]*source.complexes[r, ] == source.complexes[r, ])) {
      check <- 2
      ratesIneq[2, r] <- -1
    } else {
      for (i in 1:m) {
        e <- rep(0, m)
        e[i] <- 1
        if (all(neg == e) && all(B[i, ]*source.complexes[r, ] == source.complexes[r, ])) {
          check <- 2
          ratesIneq[2, r] <- -1
        }
      }
    }
    if (check != 2) {
      result <- 0
      firstFail <- paste('reaction', r, '/ conditions (b)')
      break
    }
  }
  return(list(result = result, rate.inequalities = ratesIneq, 
              species.inequalities = speciesIneq, first.fail = firstFail))
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

populateRC <- function(source.complexes, product.complexes) {
  checkIntegerInput(source.complexes, "source.complexes", nonnegative = TRUE)
  checkIntegerInput(product.complexes, "product.complexes", nonnegative = TRUE)
  storage.mode(source.complexes) <- "double"
  storage.mode(product.complexes) <- "double"
  n <- nrow(source.complexes)  # number of reactions
  d <- ncol(source.complexes)  # number of species
  if (nrow(product.complexes) != n) {
    stop('number of rows of matrices "source.complexes" and "product.complexes" does not match')
  }
  if ((ncol(product.complexes) != d)) {
    stop('number of columns of matrices "source.complexes" and "product.complexes" does not match')
  }
  reaction.vectors <- product.complexes-source.complexes         # matrix of reaction vectors
  # exact integer basis of S^perp, so that the matrix D of Theorem 4.1 has
  # integer entries
  K <- intKernelSI(reaction.vectors)
  conservation.laws <- if (nrow(K) == 0) matrix(rep(0, d), nrow = 1) else K
  return(list(R = reaction.vectors, C = conservation.laws))
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

toBinary <- function(decimal) {
  if (decimal == 0) {
    return('0')
  }
  binary <- ''
  while (decimal > 0) {
    binary <- paste0(decimal %% 2, binary)
    decimal <- decimal %/% 2
  }
  return(binary)
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

toSymbols <- function(inequalities.matrix) {
  vec <- c()
  n <- ncol(inequalities.matrix)
  for (i in 1:n) {
    if (all(inequalities.matrix[, i] == c(1,-1))) {
      vec[i] <- '='
    } else if (all(inequalities.matrix[, i] == c(1,0))) {
      vec[i] <- '+'
    } else if (all(inequalities.matrix[, i] == c(0,-1))) {
      vec[i] <- '-'
    } else if (all(inequalities.matrix[, i] == c(0,0))) {
      vec[i] <- '?'
    } else {
      vec[i] <- 'ERROR'
    }
  }
  return(t(as.matrix(vec)))
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

processResults <- function(orderings) {
  preorders <- list()
  equivalences <- list()
  orderings <- unique(orderings)
  l <- length(orderings)
  if (l == 0) {
    output <- list(preorders = preorders, equivalences = equivalences)
    return(output)
  } else {
    n <- ncol(orderings[[1]]$rate.inequalities)
    d <- ncol(orderings[[1]]$species.inequalities)
  }
  for (i in 1:(l-1)) {
    reverseIneq <- 0
    stop <- 0
    k <- 1
    while ((k <= n+d) && (stop == 0)) {
      if (all(cbind(orderings[[i]]$rate.inequalities, 
                    orderings[[i]]$species.inequalities)[, k] == c(0,-1))) {
        reverseIneq <- 1
        stop <- 1
      } else if (all(cbind(orderings[[i]]$rate.inequalities, 
                           orderings[[i]]$species.inequalities)[, k] == c(1,0))) 
      {
        stop <- 1
      }
      k <- k+1
    }
    if (reverseIneq == 1) {
      orderings[[i]]$rate.inequalities <- as.matrix(-orderings[[i]]$rate.inequalities[c(2,1), ])
      orderings[[i]]$species.inequalities <- 
        as.matrix(-orderings[[i]]$species.inequalities[c(2,1), ])
    }
    for (j in (i+1):l) {
      if (all(orderings[[j]]$rate.inequalities == -orderings[[i]]$rate.inequalities[c(2,1), ])) {
        orderings[[j]]$rate.inequalities <- -orderings[[j]]$rate.inequalities[c(2,1), ]
        orderings[[j]]$species.inequalities <- -orderings[[j]]$species.inequalities[c(2,1), ]
      }
    }
  }
  orderings <- unique(orderings)
  l <- length(orderings)
  ordersMatrix <- matrix(nrow = 2*(n+d), ncol = l)
  for (k in 1:l) {
    ordersMatrix[, k] <- c(abs(orderings[[k]]$rate.inequalities), 
                           abs(orderings[[k]]$species.inequalities))
  }
  sortedIndexes <- do.call(order, c(as.data.frame(t(ordersMatrix[1:(2*(n+d)), ])), 
                                    list(decreasing = TRUE)))
  orderings <- orderings[sortedIndexes]
  orderings[[l]] <- NULL
  orderings[[1]] <- NULL
  l <- length(orderings)
  if (l == 0) {
    output <- list(preorders = preorders, equivalences = equivalences)
    return(output)
  }
  for (k in 1:l) {
    orderings[[k]]$rate.inequalities <- toSymbols(orderings[[k]]$rate.inequalities)
    orderings[[k]]$species.inequalities <- toSymbols(orderings[[k]]$species.inequalities)
  }
  for (k in 1:l) {
    vec <- orderings[[k]]$species.inequalities
    if (any(vec == '+' | vec == '-')) {
      preorders <- append(preorders, list(orderings[[k]]))
    } else {
      equivalences <- append(equivalences, list(orderings[[k]]))
    }
  }
  output <- list(preorders = preorders, equivalences = equivalences)
  return(output)
}



## main functions ##################################################################################

checkOrdering <- function(source.complexes, product.complexes, preorder.matrix) {
  # compute matrices R and C
  RandC <- populateRC(source.complexes, product.complexes)
  reaction.vectors <- RandC$R
  conservation.laws <- RandC$C
  # everything can be now computed with the function checkConditions()
  output <- checkConditions(source.complexes, reaction.vectors, conservation.laws, preorder.matrix)
  output$rate.inequalities <- toSymbols(output$rate.inequalities)
  output$species.inequalities <- toSymbols(output$species.inequalities)
  if (output$result == 1) {
    cat('\n YES: the sufficient conditions of Theorem 4.1 were verified
      the trajectories can thus be ordered under the stated assumptions \n\n')
  } else {
    cat('\n NO: the sufficient conditions of Theorem 4.1 were not verified for this matrix \n\n')
  }
  return(output)
}

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

findOrderings <- function(source.complexes, product.complexes) {
  n <- nrow(source.complexes)  # number of reactions
  d <- ncol(source.complexes)  # number of species
  orderings <- newOrderingSet()
  # compute matrices reaction.vectors and conservation.laws
  RandC <- populateRC(source.complexes, product.complexes)
  reaction.vectors <- RandC$R
  conservation.laws <- RandC$C
  # try all 'simple' and essentially different orders
  E <- matrix(nrow = 2*d, ncol = d)
  for (i in 1:d) {
    e <- rep(0, d)
    e[i] <- 1
    E[i, ] <- e
    E[d+i, ] <- -e
  }
  cat('\n\n')
  if (d <= 6) {steps <- 10}
  else if (d == 7) {steps <- 20}
  else if (d == 8) {steps <- 50}
  else if (d >= 9) {steps <- 100}
  t0 <- Sys.time()
  cat(paste0(c('> PROGRESS ', rep(' ', steps-5), '%      TIME NOW     END TIME\n'), collapse = ''))
  elapsed <- 0
  cat(paste0(c('[', rep('-', steps), ']    ', 0, '      ',
               format(Sys.time(), "%H:%M:%S"), '     ESTIMATE\n'), collapse = ''))
  lastPrinted <- 0
  for (i in (2^d-1):0) {
    for (j in i:0) {
      coef1 <- as.integer(strsplit(toBinary(i), NULL)[[1]])
      l1 <- length(coef1)
      coef2 <- as.integer(strsplit(toBinary(j), NULL)[[1]])
      l2 <- length(coef2)
      coeff <- rep(0, 2*d)
      coeff[(d-l1+1):d] <- coef1
      coeff[(2*d-l2+1):(2*d)] <- coef2
      preorder.matrix <- diag(coeff) %*% E
      preorder.matrix <- preorder.matrix[apply(preorder.matrix, 1, function(x) !all(x == 0)), ]
      if (!is.matrix(preorder.matrix)) {
        preorder.matrix <- matrix(preorder.matrix, ncol = d)
      }
      check <- checkConditions(source.complexes, reaction.vectors, conservation.laws, 
                               preorder.matrix)
      if (check$result == 1) {
        addOrdering(orderings, list(rate.inequalities = check$rate.inequalities,
                                    species.inequalities = check$species.inequalities))
      }
      progress <- floor(steps*(sum((2^d):(i+1))-j)/sum((2^d):1))
      if (progress > lastPrinted) {
        elapsed <- Sys.time() - t0
        remaining <- elapsed/progress*(steps-progress)
        endtime <- Sys.time() + remaining
        if (100*progress/steps < 10) {
          cat(paste0(c('[', rep('|', progress), rep('-', steps-progress),
                       ']    ', 100*progress/steps, '      ', 
                       format(Sys.time(), "%H:%M:%S"), '     ', 
                       format(endtime, "%H:%M:%S"), '\n'), collapse = ''))
        } else if (100*progress/steps == 100) {
          cat(paste0(c('[', rep('|', progress), rep('-', steps-progress),
                       ']    ', 100*progress/steps, '    ', 
                       format(Sys.time(), "%H:%M:%S"), '     ', 
                       format(endtime, "%H:%M:%S"), '\n'), collapse = ''))
        } else {
          cat(paste0(c('[', rep('|', progress), rep('-', steps-progress),
                       ']    ', 100*progress/steps, '     ', 
                       format(Sys.time(), "%H:%M:%S"), '     ', 
                       format(endtime, "%H:%M:%S"), '\n'), collapse = ''))
        }
        lastPrinted <- progress
      }
    }
  }
  cat('\n')
  orderings <- processCanonical(orderingSetToList(orderings))
  cat(paste0(length(orderings$preorders), ' PREORDERS (', 2*length(orderings$preorders), 
             ' with their opposites) and ', length(orderings$equivalences), 
             ' EQUIVALENCES were found\n\n\n'))
  return(orderings)
}


## exact arithmetic ################################################################################

# Numeric inputs must already be exact finite integers. Values at or above
# 2^53 are rejected at the input boundary, where rounding may already have
# occurred. The boundary itself is allowed for internally computed laws.
checkIntegerInput <- function(x, name, nonnegative = FALSE, allow.boundary = FALSE) {
  if (!is.numeric(x) || is.complex(x) || any(!is.finite(x)) ||
      any(x != trunc(x)))
    stop(name, ": entries must be finite integers")
  too.large <- if (allow.boundary) abs(x) > 2^53 else abs(x) >= 2^53
  if (any(too.large))
    stop(name, ": entries are outside the supported exact integer range")
  if (nonnegative && any(x < 0))
    stop(name, ": entries must be nonnegative")
  invisible(NULL)
}

# The products M xi_r, one column per reaction, computed exactly.  When every
# entry of M is at most a and every entry of R at most b in absolute value, each
# product is an integer of absolute value at most ab, and any partial sum of a
# row-by-column product is an integer of absolute value at most d ab.  Below 2^53
# every such integer is a double and every operation on them is exact, whatever
# order the products are summed in; beyond that bound the product is formed in
# GMP integers and converted back only if it fits.
exactProduct <- function(M, R) {
  checkIntegerInput(M, "preorder.matrix")
  checkIntegerInput(R, "reaction.vectors")
  if (ncol(M) != ncol(R)) stop("exactProduct(): incompatible dimensions")
  if (max(abs(M), 0) * max(abs(R), 0) * ncol(M) < 2^53) return(M %*% t(R))
  Z <- gmp::as.bigz(M) %*% t(gmp::as.bigz(R))
  if (any(abs(Z) > gmp::as.bigz(2)^53))
    stop("exactProduct(): exact product outside the supported numeric range")
  matrix(as.numeric(Z), nrow = nrow(M))
}

# The i-th rows of A and of B at once.  A[i,j] asks whether e_j lies in the cone
# generated by the columns of D, and B[i,j] asks the same of -e_j; all 2d
# questions concern that one cone, which is described here by its facets.
# cddlib returns rows (l, b, H) meaning
# b + H x >= 0, with equality where l = 1, and b = 0 for a cone through the
# origin -- so membership of +/- e_j is just the sign pattern of the j-th COLUMN
# of H.  Everything is rational, so the answers are exact.
coneRow <- function(D, d) {
  k <- ncol(D)
  vrep <- rbind(cbind(d2q(0), d2q(1), d2q(matrix(0, 1, d))),          # the origin, a point
                cbind(d2q(rep(0, k)), d2q(rep(0, k)), d2q(t(D))))     # the generators, rays
  h <- tryCatch(scdd(vrep)$output, error = function(e) NULL)
  if (is.null(h)) return(coneRowByLP(D, d))   # fall back if the facet enumeration fails
  lin <- h[, 1] == "1"
  H <- h[, -c(1, 2), drop = FALSE]
  a <- rep(0, d); b <- rep(0, d)
  for (j in 1:d) {
    s <- qsign(H[, j])
    a[j] <- all(s[!lin] >= 0) && all(s[lin] == 0)
    b[j] <- all(s[!lin] <= 0) && all(s[lin] == 0)
  }
  list(a = a, b = b)
}

# The same row, one exact feasibility problem at a time.  Used when the double
# description of the cone is unavailable.
coneRowByLP <- function(D, d) {
  a <- rep(0, d); b <- rep(0, d)
  for (j in 1:d) {
    e <- rep(0, d); e[j] <- 1
    a[j] <- feasibleQ(D,  e)
    b[j] <- feasibleQ(D, -e)
  }
  list(a = a, b = b)
}

# Exact rational feasibility: is there z >= 0 with D z = e ?
feasibleQ <- function(D, e) {
  k <- ncol(D)
  hrep <- makeH(a1 = d2q(-diag(k)), b1 = d2q(rep(0, k)),   # -z <= 0
                a2 = d2q(D),        b2 = d2q(e))           #  D z = e
  lpcdd(hrep, objgrd = d2q(rep(0, k)), minimize = TRUE)$solution.type == "Optimal"
}

# Which rows of A and B can checkConditions() consult?  Row m+1 always, through
# (a2) and (b2); row i only when some reaction has (M xi_r)^+ = e_i or
# (M xi_r)^- = e_i, which is what (a3) and (b3) ask for.  No other row is read.
# V holds the vectors M xi_r as its columns.
neededRows <- function(V) {
  m <- nrow(V)
  need <- m + 1
  for (r in seq_len(ncol(V))) {
    vec <- V[, r]
    for (v in list(vec*(vec>0), -vec*(vec<0))) {
      if (sum(v != 0) == 1 && max(v) == 1) need <- c(need, which(v == 1))
    }
  }
  sort(unique(need))
}

# The orientation of an ordering is a function of that ordering alone: scan the
# columns of cbind(rate, species) for the first strict inequality and flip if it
# reads ">=".  The map x -> -x[c(2,1), ] that reverses every inequality exchanges
# (1,0) and (0,-1) and fixes (1,-1) and (0,0), so an ordering and its reverse have
# their first strict column in the same position and orient to the same thing,
# while an ordering with no strict column is its own reverse.  Orienting on
# arrival is therefore exactly the quotient by that symmetry, and a set keyed on
# the result holds one representative of each pair.
canonicalise <- function(o) {
  cols <- cbind(o$rate.inequalities, o$species.inequalities)
  for (k in seq_len(ncol(cols))) {
    if (all(cols[, k] == c(0, -1))) {
      o$rate.inequalities <- as.matrix(-o$rate.inequalities[c(2, 1), ])
      o$species.inequalities <- as.matrix(-o$species.inequalities[c(2, 1), ])
      return(o)
    }
    if (all(cols[, k] == c(1, 0))) return(o)
  }
  o
}

orderingKey <- function(o) paste0(paste(o$rate.inequalities, collapse = ","), "|",
                                  paste(o$species.inequalities, collapse = ","))

newOrderingSet <- function() new.env(hash = TRUE, parent = emptyenv())

addOrdering <- function(set, o) {
  o <- canonicalise(o)
  k <- orderingKey(o)
  if (!exists(k, envir = set, inherits = FALSE)) assign(k, o, envir = set)
  invisible(NULL)
}

orderingSetToList <- function(set) unname(as.list(set))

# Sort the distinct orderings, drop the two trivial structures, render the
# inequalities as symbols and separate the preorders from the equivalences.
processCanonical <- function(orderings) {
  preorders <- list(); equivalences <- list()
  l <- length(orderings)
  if (l == 0) return(list(preorders = preorders, equivalences = equivalences))
  n <- ncol(orderings[[1]]$rate.inequalities)
  d <- ncol(orderings[[1]]$species.inequalities)
  ordersMatrix <- matrix(nrow = 2*(n+d), ncol = l)
  for (k in 1:l) {
    ordersMatrix[, k] <- c(abs(orderings[[k]]$rate.inequalities),
                           abs(orderings[[k]]$species.inequalities))
  }
  sortedIndexes <- do.call(order, c(as.data.frame(t(ordersMatrix[1:(2*(n+d)), ])),
                                    list(decreasing = TRUE)))
  orderings <- orderings[sortedIndexes]
  orderings[[l]] <- NULL
  orderings[[1]] <- NULL
  l <- length(orderings)
  if (l == 0) return(list(preorders = preorders, equivalences = equivalences))
  for (k in 1:l) {
    orderings[[k]]$rate.inequalities <- toSymbols(orderings[[k]]$rate.inequalities)
    orderings[[k]]$species.inequalities <- toSymbols(orderings[[k]]$species.inequalities)
  }
  for (k in 1:l) {
    vec <- orderings[[k]]$species.inequalities
    if (any(vec == '+' | vec == '-')) preorders <- append(preorders, list(orderings[[k]]))
    else equivalences <- append(equivalences, list(orderings[[k]]))
  }
  list(preorders = preorders, equivalences = equivalences)
}

# Conservation laws by the Gauss-Jordan method of Sauro & Ingalls (2004), Sec. 4.2,
# carried out in arbitrary-precision integers.  Augment N = t(Xi) as [N | I] and row
# reduce; the rows whose N-part vanishes carry a basis of the left null space of N in
# their I-part.  Every entry is a GMP integer from the start, so no row operation can
# leave the exact range or cancel silently, and the basis is checked against Xi before
# it is returned.
intKernelSI <- function(Xi) {
  checkIntegerInput(Xi, "reaction.vectors")
  d <- ncol(Xi)
  N <- t(Xi)                                                  # species x reactions
  if (any(abs(N - round(N)) > 0)) stop("intKernelSI(): reaction vectors must be integers")
  n <- ncol(N)
  zero <- as.bigz(0)
  A <- as.bigz(cbind(round(N), diag(1, d)))                   # [N | I], exact integers
  dim(A) <- c(d, n + d)
  r <- 1
  for (cc in seq_len(n)) {
    if (r > d) break
    p <- which(A[r:d, cc] != zero)
    if (!length(p)) next
    p <- p[1] + r - 1
    if (p != r) { tmp <- A[r, ]; A[r, ] <- A[p, ]; A[p, ] <- tmp }
    for (k in seq_len(d)) {
      if (k != r && A[k, cc] != zero) {
        g <- gcd.bigz(A[k, cc], A[r, cc])
        a <- divq.bigz(A[r, cc], g); b <- divq.bigz(A[k, cc], g)
        A[k, ] <- a * A[k, ] - b * A[r, ]
        A[k, ] <- divq.bigz(A[k, ], primitiveZ(A[k, ]))
      }
    }
    r <- r + 1
  }
  npiv <- r - 1                                               # rank of N, exactly
  keep <- integer(0)
  for (i in seq_len(d)) if (all(A[i, seq_len(n)] == zero)) keep <- c(keep, i)
  if (length(keep) != d - npiv) stop("intKernelSI(): wrong number of conservation laws")
  if (!length(keep)) return(matrix(numeric(0), nrow = 0, ncol = d))
  G <- matrix(0, nrow = length(keep), ncol = d)
  lim <- as.bigz(2)^53                                        # exact range of a double
  for (i in seq_along(keep)) {
    v <- A[keep[i], n + seq_len(d)]
    v <- divq.bigz(v, primitiveZ(v))                          # primitive integer row
    for (j in seq_len(nrow(Xi)))                              # exact check: C Xi^T = 0
      if (sum(v * as.bigz(round(Xi[j, ]))) != zero)
        stop("intKernelSI(): computed row is not a conservation law")
    if (any(abs(v) > lim))
      stop("intKernelSI(): conservation law outside the exact range of a double")
    G[i, ] <- as.numeric(v)
  }
  G
}

# content of a vector of exact integers, signed by its leading non-zero entry
primitiveZ <- function(v) {
  nz <- v[v != as.bigz(0)]
  if (!length(nz)) return(as.bigz(1))
  g <- abs(nz[1])
  for (j in seq_along(nz)[-1]) g <- gcd.bigz(g, abs(nz[j]))
  if (nz[1] < 0) -g else g
}
